resolver: nightly-2025-10-07
packages:
  - .
extra-deps:
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 62c84930b790b43b8f1f8cbaed7ca5255c17a87e
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/output-blocks.git
    commit: d67590cb2e1a72ed72437a8cfe2972b680405569
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/autotool-capabilities.git
    commit: 9001e5040f2a48337359c6d93f600420d17b3dcc
    subdirs:
      - autotool-capabilities
      - autotool-capabilities-io-instances
  - git: https://github.com/fmidue/logic-tasks.git
    commit: af94e0ba22ffd4e679bdd19f0da31ee60a7784f1
  - git: https://github.com/fmidue/term-tasks
    commit: e689627e43c800e7da4b440de6ab6aae07c4ec44
  - latex-svg-image-0.2@sha256:b282a74a96724037ec3d24b664118e51170c8152aff12f363ddb715a38ef053a,1830
  - diagrams-graphviz-1.4.1.1@sha256:36c02a7ff8ac60cf098c73a98abbff1eaa6fa759be42f0c2dcfe8083761b1ec0,1482
  - git: https://github.com/fmidue/modelling-tasks
    commit: 145b36f7bcbfc4d4cc57b5be5eb81854b7b95069
  - git: https://github.com/fmidue/IOTasks
    commit: 7ef09585a8d703a1eb6992dcb0349af5de40cfdc
  # dependencies for IOTasks
  - git: https://github.com/IagoAbal/haskell-z3
    commit: 6368e451e45359563106da7e917f6594453c5161
  - git: https://github.com/owestphal/type-match
    commit: e1afab43d2e8bfa5e2006492ed34060036e7be51
  # for output-blocks
  - git: https://git.uni-due.de/fmi/autotool-dev.git
    commit: 849d725e7284e87e077af136ccc3140d824679e8
    subdirs:
      - base
      - data
      - reader
      - todoc
      - transport
      - util

allow-newer: true
