resolver: nightly-2024-03-20
packages:
  - .
extra-deps:
  - git: https://github.com/fmidue/flex-tasks.git
    commit: 607d96ed5dc606e473513aa054a766793b0d0524
    subdirs:
      - flex-tasks
      - flex-tasks-processing
  - git: https://github.com/fmidue/output-blocks.git
    commit: e97c5f06a17c5b99f0bed2a733bfbf974304adf3
    subdirs:
      - output-blocks
  - git: https://github.com/fmidue/autotool-capabilities.git
    commit: abf9b15ad431e517ae0700ad9dfb6f6941e10538
    subdirs:
      - autotool-capabilities
      - autotool-capabilities-io-instances
  - git: https://github.com/fmidue/logic-tasks.git
    commit: d4281a454117b6377f74ab25eb472ed7e5edaaa3
  - git: https://github.com/fmidue/term-tasks
    commit: cb2bfac5e0145c01fbbab7e4f995d624db72dcad
  - latex-svg-image-0.2@sha256:b282a74a96724037ec3d24b664118e51170c8152aff12f363ddb715a38ef053a,1830
  - call-alloy-0.6.0.2@sha256:f7ecb0f4b8f7cc804d6d8ace7c323b48e3aa03994a2d09c4b7ee66cc4bf15abd,3850
  - diagrams-graphviz-1.4.1.1@sha256:36c02a7ff8ac60cf098c73a98abbff1eaa6fa759be42f0c2dcfe8083761b1ec0,1482
  - git: https://github.com/fmidue/modelling-tasks
    commit: 3df8b73de291d60f589c4709749410f9b562c7b6
  - git: https://github.com/fmidue/IOTasks
    commit: 21a9d1f159f3d447ba747036e164d6dc29dbbd73
  # dependencies for IOTasks
  - git: https://github.com/IagoAbal/haskell-z3
    commit: 6368e451e45359563106da7e917f6594453c5161
  - git: https://github.com/owestphal/type-match
    commit: e1afab43d2e8bfa5e2006492ed34060036e7be51

allow-newer: true
allow-newer-deps:
  - latex-svg-image
